apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-html
spec:
  capacity:
    storage: 1T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /hdd/blog
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - tymur999srv